language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3

before_install:
    - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
    - gem install bundler -v '< 2'
    - sudo apt-get update -y
    - sudo apt-get install -y shared-mime-info

after_success:
  - coveralls
